title: Blockchain at NTUsg
email: blockchain.ntusg@gmail.com
description: 'Blockchain@NTU is a student initiated club dedicated to foster a vibrant blockchain community in NTU Singapore and beyond through education, research and development and consulting.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.ntublockchain.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  ntusg-blockchain
future: true
excerpt_separator: '---'
timezone: Asia/Singapore
# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
sass:
  load_paths:
    - _sass
    - css
    - node_modules
  style: compressed
exclude:
  - node_modules
  - README.md
  - LICENSE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - script
  - spec
  - vendor
include:
  - _pages
